name: github-issue-auto-assign

on:
  pull_request:
    type:
      - opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto_assign_configs.yml'