name: Staging deploy flow

on:
#  push:
#    branches:
#      - fakemaster
  workflow_dispatch:
    inputs:
      target_version:
        description: "The target version (x.x.x-x)"
        type: string
        required: true

env:
#  staging_branch: staging/${{ inputs.target_version }}
  staging_branch: staging/1.1.1

jobs:
  Build-changelog:
    runs-on: ubuntu-latest
    outputs:
      staging_branch: ${{ env.staging_branch }}
      titles: ${{ steps.fetch-pr.outputs.titles }}
    steps:
#      - name: Fail if branch is not main
#        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/fakemaster'
#        run: |
#          echo "This workflow should not be triggered with workflow_dispatch on a branch other than fakemaster"
#          exit 1
#
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Create beta branch"
        id: new-branch
        run: |
          git checkout -b ${{ env.staging_branch }}

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@3.7.2
        with:
          configuration: ".github/changelog_configs.json"

      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.staging_branch }}

  Bump-version:
    needs: [ Build-changelog ]
    uses: ./.github/workflows/use-case-bump-version.yaml
    secrets: inherit
    with:
#      version: ${{ inputs.target_version }}
      version: 1.1.1

  Merge-to-release:
    needs: [ Bump-version ]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0

      - name: "Merge to release"
        run: |
          git merge --squash "origin/${{ env.staging_branch }}"
          git commit -m "release staging version: '${{ env.staging_branch }}'"
      - name: "Push release"
        uses: ad-m/github-push-action@master
        with:
          branch: release
